# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

app_store_connect_api_key(
  key_id: "7FN57R567Z",
  issuer_id: "69a6de88-7946-47e3-e053-5b8c7c11a4d1",
  key_filepath: "/Users/smart/Projects/FlutterGimchi/fastlaneAuthKeys/AuthKey_7FN57R567Z.p8"
)

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store(
  	skip_metadata: true,
  	skip_screenshots: true,
  	skip_app_version_update: true,
  	precheck_include_in_app_purchases: false
   	)
  end
end
